spring:
  application:
    name: usernatching
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1m
        max-idle: 8
  reactorurl:
    dbserviceurl: http://localhost:8001
server:
  port: 8088
#
#logfile:
#  path: E:\logfils\PhoneErro
RedisDBIndex:
  matchingRedisDBIndex: 0
  smsCodeRedisDBIndex: 1
  UCodeRedisDBIndex: 2
